name: Bot Auto Run

on:
  schedule:
    - cron: '0 */6 * * *'   # Auto run every 6 hours (UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360     # Max 6 hours per job

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start bot in background
      run: |
        nohup npm start > bot.log 2>&1 &
        sleep 10
        echo "Bot started in background"
